
[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/shoenig/toolkit"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"
